
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Pasan
 */
public class setTimetable extends javax.swing.JFrame {

    /**
     * Creates new form setTimetable
     */
    public setTimetable() {
        initComponents();
        connect();
    }
            Connection conn;
            PreparedStatement ps;
    
    
    public void connect(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Regpage.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            conn=DriverManager.getConnection("jdbc:mysql://localhost/schooltimetable","root","");
        } catch (SQLException ex) {
            Logger.getLogger(Regpage.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rid = new javax.swing.JTextField();
        cbclass = new javax.swing.JComboBox<>();
        cbdays = new javax.swing.JComboBox<>();
        sub = new javax.swing.JTextField();
        cbtime = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        jButton5.setText("jButton5");

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setText("Set Timetable");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(574, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        jLabel2.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Class");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 143, -1, -1));

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Day");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 192, -1, -1));

        jLabel4.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Subject");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 253, -1, -1));

        jLabel5.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Time");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 311, -1, -1));

        jLabel6.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Record id");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 99, -1, -1));

        rid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ridActionPerformed(evt);
            }
        });
        getContentPane().add(rid, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 94, 152, -1));

        cbclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6A", "6B", "7A", "7B", "8C" }));
        getContentPane().add(cbclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 138, 152, -1));

        cbdays.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday" }));
        getContentPane().add(cbdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 187, 152, -1));
        getContentPane().add(sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 248, 152, -1));

        cbtime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8:00A.M - 8:40A.M", "8:40A.M - 9:20A.M", "9:20A.M - 10:00A.M", "10:40A.M-11:00A.M", "----INTERWAL----", "11:00A.M - 11:40A.M", "11:40A.M - 12:20P.M", "12:20P.M - 1:00P.M", "1:00P.M - 1:40P.M" }));
        getContentPane().add(cbtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 306, 152, -1));

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 374, -1, -1));

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton2.setText("Update ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 374, -1, -1));

        jButton3.setBackground(new java.awt.Color(153, 255, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton3.setText("delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 374, -1, -1));

        jButton4.setBackground(new java.awt.Color(153, 255, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton4.setText("timetable view");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 374, -1, -1));

        jButton6.setBackground(new java.awt.Color(153, 255, 255));
        jButton6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton6.setText("Menu");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 374, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\images project\\4.jpg")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 640, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ridActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String classname=(String)cbclass.getSelectedItem();
        String day=(String)cbdays.getSelectedItem();
        String subT=sub.getText();
        String Time=(String)cbtime.getSelectedItem();
        
        
if(classname.equals("")){
            JOptionPane.showMessageDialog(null,"class name shoul be selected");
        }

else if(day.equals("")){
            JOptionPane.showMessageDialog(null,"day should be selected");
        }

else if(subT.equals("")){
            JOptionPane.showMessageDialog(null,"subject must be entered");
        }
else if(Time.equals("")){
            JOptionPane.showMessageDialog(null,"time period must be selected");


}



else{
    
            try {
                ps=conn.prepareStatement("insert into timetable(class,day,T_subject,time)values(?,?,?,?)");
                ps.setString(1,classname);
                ps.setString(2,day);
                ps.setString(3,subT);
                ps.setString(4,Time);
                
                
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this,"timetable record saved successfully");
                
                cbclass.setSelectedIndex(-1);
                cbdays.setSelectedIndex(-1);
                cbtime.setSelectedIndex(-1);
                sub.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(setTimetable.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String recordID=rid.getText();
        String classname=(String)cbclass.getSelectedItem();
        String day=(String)cbdays.getSelectedItem();
        String subT=sub.getText();
        String Time=(String)cbtime.getSelectedItem();
        
        
if(classname.equals("")){
            JOptionPane.showMessageDialog(null,"class name shoul be selected");
        }

else if(day.equals("")){
            JOptionPane.showMessageDialog(null,"day should be selected");
        }

else if(subT.equals("")){
            JOptionPane.showMessageDialog(null,"subject must be entered");
        }
else if(Time.equals("")){
            JOptionPane.showMessageDialog(null,"time period must be selected");


}
else if(recordID.equals("")){
            JOptionPane.showMessageDialog(null,"record id must be entered");


}




else{
    
            try {
                ps=conn.prepareStatement("UPDATE timetable set class=?,day=?,T_subject=?,time=? where R_id=?");
                ps.setString(1,classname);
                ps.setString(2,day);
                ps.setString(3,subT);
                ps.setString(4,Time);
                ps.setString(5,recordID);
                
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this,"record is updated successfully");
                
                cbclass.setSelectedIndex(-1);
                cbdays.setSelectedIndex(-1);
                cbtime.setSelectedIndex(-1);
                sub.setText("");
                rid.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(setTimetable.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String recordID=rid.getText();
        if(recordID.equals("")){
            JOptionPane.showMessageDialog(null,"record id should be entered");
        }else{
            try {
                ps=conn.prepareStatement("delete from timetable where R_id=?");
                ps.setString(1,recordID);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this,"record is deleted successfully");
                rid.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(setTimetable.class.getName()).log(Level.SEVERE, null, ex);
            }
          
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
              
              viewTimetable vt= new viewTimetable();
              vt.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        dispose();
              AdminMenu ad= new AdminMenu();
              ad.setVisible(true);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(setTimetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(setTimetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(setTimetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(setTimetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new setTimetable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbclass;
    private javax.swing.JComboBox<String> cbdays;
    private javax.swing.JComboBox<String> cbtime;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField rid;
    private javax.swing.JTextField sub;
    // End of variables declaration//GEN-END:variables
}
